### PR TITLE
Update use cases for sortpj and unassign commands

### PR DESCRIPTION
**Pull request by dillongoh**
DeveloperGuide.md:
* Add use case for sorting projects
* Add use case for unassigning a member
* Fix typo in UC04

### CODE REVIEW

**Review by chia-yh — COMMENTED** [review]
2 main issues:

1. Perhaps consider specifying "displays the sorted **contact/project** list" to remove any sort of ambiguity, even if it's obvious.

2. Refer to the below image
image
I've avoided adding any use cases for projects as of yet, as I feel it raises the same issue in the screenshot; I was considering bringing up the issue during the meeting, however since we're at this point already: @cmang12 @huanghao1998 @nus-jeff , could I request your thoughts on using "Similar to use case ___ except..." for use cases relevant to project? If we do decide to go in this direction, I think the only commands excluded from this scenario are assign/unassign, as they are "unique".

**Comment by cmang12** [comment]
I don't really see an issue with using "Similar to use case ___ except..." as long as we're sure that it doesn't hide any details specific to that feature. Though maybe one concern that it may be confusing to the user, following the image, would it be like "Similar to use case 7 except "edit" instead of "add" ?

**Comment by chia-yh** [comment]
I think the current implementation of commands for persons are distinct enough that there’s no need to merge the use cases (within those concerning persons), so the usage of “Similar to use case x except…” would be for the equivalent project commands excluding assign and unassign as there’re not really equivalents.

I agree on the inclusion of specificities, so just off the top of my head the key things we’d have to include would be:
* applied to projects instead
* potentially different extensions
Since the use cases themselves exclude lower level details and such of the implementation, the use case equivalents for persons and projects would appear similar after all

**Comment by cmang12** [comment]
Yes I agree that we should just use this convention for Projects and not merge use cases within Persons

**Comment by dillongoh** [comment]
Sounds good that's probably better

**Comment by huanghao1998** [comment]
I agree on that too! 👍

**Review by chia-yh — APPROVED** [review]
LGTM, @nus-jeff if you have any objections we can correct this in the future

**Pull request merged**
