### PR TITLE
Restriction on number of tags

### PR DESCRIPTION
**Pull request by huanghao1998**
Whats change
- Restrict the number of tag being read; throws exception when tags exceeds 10

AddCommand/EditCommand.java
- Update MESSAGE_USAGE that only 10 tags will be restricted.
- Throw exception when the tags exceeds 10 tags.

Update the test case for throw exception

### CODE REVIEW

**Review by dillongoh — COMMENTED** [review]
While this implementation works to prevent overloading the GUI with too many tags, Do you intend to prevent the user from adding more than 10 tags? eg. by throwing an exception

**Comment by huanghao1998** [comment]
> While this implementation works to prevent overloading the GUI with too many tags, Do you intend to prevent the user from adding more than 10 tags? eg. by throwing an exception

No going to have an exception, as this may affects the user experience. For example, user type more 10 tags but program throws an exception which would need them to retype all the tags.

**Comment by dillongoh** [comment]
I believe that user experience would be equally affected if you were to allow users to add more than 10 tags but not display them. A user who does not read the user guide would not understand the behavior. Requesting input from @chia-yh @cmang12 @nus-jeff so we can decide on a suitable implementation.

**Comment by huanghao1998** [comment]
> I believe that user experience would be equally affected if you were to allow users to add more than 10 tags but not display them. A user who does not read the user guide would not understand the behavior. Requesting input from @chia-yh @cmang12 @nus-jeff so we can decide on a suitable implementation.

I update the changes to throwing exception, I realised the input text will be retained in the text field even when the program throws exception. @dillongoh Thanks for the suggestion.

**Review by dillongoh — APPROVED** [review]
LGTM 👍

**Pull request merged**
